### PR TITLE
fix memory leaks.

### PR DESCRIPTION
**Pull request by ihsinme**
the function has the ability to exit without first clearing the allocated memory.

### CODE REVIEW

**Comment by dbry** [comment]
Thanks for this, good catch! I have some local changes I'm working on so I'll leave this up here for a bit until I can merge it cleanly.

**Comment by ihsinme** [comment]
is there any news on this PR?

**Comment by dbry** [comment]
Hi. I took a look at this and I don't understand why you are freeing `out2filename_temp` but not `outfilename_temp` also?

It seems like the same change would apply to that.

If you fix that I'll merge this in.

Thanks!

**Comment by ihsinme** [comment]
yes, at first glance, you are right. I will certainly fix this shortly.

**Comment by zodf0055980** [comment]
You forget add `;` in wavpack.c:1830

**Comment by ihsinme** [comment]
fix in https://github.com/dbry/WavPack/pull/89  
I apologize for this mistake.

**Pull request merged**
