### PR TITLE
Let CMake build the same libraries as autotools

### PR DESCRIPTION
**Pull request by madebr**
Before, the .so libraries installed by the cmake toolchain were not versioned.
Fix this by extracting the libtool versioning from `configure.ac` and convert these to so version numbers.
Also use this extracted version to make sure the installed mingw dll binary is named the same.

MinGW CMake prefix:
```
prefix
├── bin
│   ├── libwavpack-1.dll
│   ├── wavpack.exe
│   ├── wvgain.exe
│   ├── wvtag.exe
│   └── wvunpack.exe
├── cmake
│   ├── wavpack-config.cmake
│   ├── wavpack-config-noconfig.cmake
│   └── wavpack-config-version.cmake
├── include
│   └── wavpack
│       └── wavpack.h
├── lib
│   ├── libwavpack.dll.a
│   └── pkgconfig
│       └── wavpack.pc
└── share
    └── man
        └── man1
            ├── wavpack.1
            ├── wvgain.1
            ├── wvtag.1
            └── wvunpack.1
```

Linux CMake prefix:
```
prefix
├── bin
│   ├── wavpack
│   ├── wvgain
│   ├── wvtag
│   └── wvunpack
├── include
│   └── wavpack
│       └── wavpack.h
├── lib64
│   ├── cmake
│   │   └── WavPack
│   │       ├── wavpack-config.cmake
│   │       ├── wavpack-config-noconfig.cmake
│   │       └── wavpack-config-version.cmake
│   ├── libwavpack.so -> libwavpack.so.1
│   ├── libwavpack.so.1 -> libwavpack.so.1.2.5
│   ├── libwavpack.so.1.2.5
│   └── pkgconfig
│       └── wavpack.pc
└── share
    └── man
        └── man1
            ├── wavpack.1
            ├── wvgain.1
            ├── wvtag.1
            └── wvunpack.1
```

@sezero, can you verify on Macos?

### CODE REVIEW

**Comment by sezero** [comment]
> @sezero, can you verify on Macos?

Cross-compile results on linux:

With autotools:
```
$ ls -l ./lib/*dylib
-rwxr-xr-x. 1 ozzie ozzie 172780 Dec  9 22:04 ./lib/libwavpack.1.dylib
lrwxrwxrwx. 1 ozzie ozzie     18 Dec  9 22:04 ./lib/libwavpack.dylib -> libwavpack.1.dylib

$ i686-apple-darwin9-otool -L ./lib/libwavpack.dylib
./lib/libwavpack.1.dylib:
	/home/ozzie/w1/lib/libwavpack.1.dylib (compatibility version 4.0.0, current version 4.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.10)
```

With cmake using this patch:
```
$ ls -l ./lib/*dylib
-rwxr-xr-x. 1 ozzie ozzie 223592 Dec  9 22:12 ./lib/libwavpack.dylib

$ i686-apple-darwin9-otool -L ./lib/libwavpack.dylib
./lib/libwavpack.dylib:
	libwavpack.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.10)
```

**Comment by sezero** [comment]
OK, after a4a6402b it does match autotools, except for install_name
which should have something to do with RPATH I guess...
```
$ ls -l ./lib/*dylib
-rwxr-xr-x. 1 ozzie ozzie 223592 Dec 10 01:08 ./lib/libwavpack.1.dylib
lrwxrwxrwx. 1 ozzie ozzie     18 Dec 10 01:08 ./lib/libwavpack.dylib -> libwavpack.1.dylib

$ i686-apple-darwin9-otool -L ./lib/libwavpack.dylib
./lib/libwavpack.dylib:
	libwavpack.1.dylib (compatibility version 4.0.0, current version 4.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.10)
```

**Review by sezero — APPROVED** [review]

**Comment by madebr** [comment]
CMake removes rpath on installation. Don't know what libtool does.

**Comment by sezero** [comment]
> CMake removes rpath on installation.

Looks like it, but ugh..

> Don't know what libtool does.

Seems to set it according to install location and keeps it.

**Comment by dbry** [comment]
@evpobr , since you are the initial contributor here, does this all seem reasonable? It certainly looks good to me. Thanks!

**Comment by evpobr** [comment]
Good!

**Comment by dbry** [comment]
> Good!

Thanks!

**Pull request merged**
