### PR TITLE
cmake: Install header in same location

### PR DESCRIPTION
**Pull request by diizzyy**
CMake currently installs header file in root of includedir while a GNU Autotools installs in wavpack/.  Consumers expect to find the header in the latter so make sure to use the same path

### CODE REVIEW

**Comment by dbry** [comment]
This is not an area I know much about, but I am used to the include file being in `/usr/local/include/wavpack/`

@evpobr should this just go in?

Thanks!

**Comment by evpobr** [comment]
It looks like it. But I don't see the code that does it, only this:

https://github.com/dbry/WavPack/blob/b9efddc4a5fb63294cd8be63716d3d8da3efc137/Makefile.am#L101

**Comment by evpobr** [comment]
If so, then it will be necessary to correct this line as well:

https://github.com/dbry/WavPack/blob/b9efddc4a5fb63294cd8be63716d3d8da3efc137/CMakeLists.txt#L204

About `CMAKE_INSTALL_INCLUDEDIR`: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html

**Comment by evpobr** [comment]
And this:

https://github.com/dbry/WavPack/blob/b9efddc4a5fb63294cd8be63716d3d8da3efc137/CMakeLists.txt#L652

**Comment by diizzyy** [comment]
204 is also correct?
652 would break thinkgs as users expect to find the header in wavpack/wavpack.h not wavpack.h so changing that part would be wrong?

**Comment by evpobr** [comment]
My mistake. If user must include `wavack/wavpack.h`, not `wavpack.h`, you don't need my changes.

**Comment by dbry** [comment]
Okay @evpobr and @diizzyy, so this is good to go in as is? Thanks!

**Comment by diizzyy** [comment]
Yes

**Comment by evpobr** [comment]
Yes 😊

**Pull request merged**
